### PR TITLE
Great improvement of PNG image sizes

### PR DESCRIPTION
**Pull request by Dade88**
- abetterbrowser-132.png : 3,08 kb to 898 b (~29% of original file size)
- abetterbrowser-200.png : 4,21 kb to 1,46 kb (~34% of original file
size)
- example.png : 7,28 kb to 4,51 kb (~62% of original file size)

### CODE REVIEW

**Comment by theaqua** [comment]
Why not. Thanks.

**Comment by Dade88** [comment]
Sorry, I am not very used with GitHub but did the pull request was approved or something?
I am asking because I still see the old images on main repository. Glad anyway if it has been helpfull for anyone else :)

**Comment by theaqua** [comment]
I forgot merge 😂

**Comment by Dade88** [comment]
:+1:

**Pull request merged**
